# Generated by Django 3.2 on 2021-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Status', models.CharField(choices=[('c', 'completed'), ('f', 'PENDING')], default='f', max_length=2)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=2)),
            ],
        ),
    ]
