# Generated by Django 3.2 on 2021-04-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo2', '0004_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Status',
            field=models.CharField(choices=[('comp', 'completed'), ('pend', 'PENDING')], default='Pend', max_length=9),
        ),
    ]
